name: auto approve pr

on:
  pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: github.head_ref == 'refs/heads/master' && github.base_ref == 'refs/heads/develop'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"